# Generated by Django 6.0.4 on 2026-04-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True, default='')),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
