# Generated by Django 4.2.30 on 2026-04-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='theme',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
